config/routes.rb
Rails.application.routes.draw do
  root    'posts#index'
  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'
  resources :users, only: [:show]
  resources :posts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 300 }
  validates :body, presence: true, length: { maximum: 40000 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  before_save :downcase_email
  before_create :set_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { in: 6..16 }

  # Returns a random 22 length token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def create_remember_token
    Digest::SHA1.hexdigest(User.new_token)
  end

  def set_remember_token
    self.remember_token = create_remember_token
  end

  private

    def downcase_email
      email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def index
    @posts = Post.paginate(page: params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = 'Post created'
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

    def post_params
      params.require(:post).permit(:title, :body)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:info] = 'Please log in first'
        redirect_to login_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      log_in(@user)
      flash[:success] = 'Successfully logged in'
      redirect_back_or(@user)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = 'Successfully logged out' 
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns a custom title based on input
  def full_title(page_title = '')
    base_title = 'Clubhouse'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    remember_token = user.create_remember_token
    user.update_attribute(:remember_token, remember_token)
    cookies.permanent.signed[:remember_token] = remember_token
    current_user
  end

  def current_user
    @current_user ||=  User.find_by(remember_token: cookies.signed[:remember_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    @current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:fowarding_url] || default)
    session.delete(:fowarding_url)
  end

  def store_location
    session[:fowarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <%= link_to 'Clubhouse', root_path, class: 'navbar-brand' %>
  <ul class="navbar-links ml-auto">
    <li class="nav-item"><%= link_to 'Home', root_path, class: 'nav-link' %></li>
    <% if logged_in? %>
      <li class="nav-item"><%= link_to 'Profile', user_path(current_user), class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link', 
          data: { confirm: 'Are you sure you want to log out?' } %></li>
    <% else %>
      <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_rails_default_head_tags.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default_head_tags' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </main>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="card border-dark mb-4">
  <% if logged_in? %>
    <div class="card-header"><%= post.user.name %></div>
  <% end %>
  <div class="card-body text-dark">
    <p class="card-title h3"><%= post.title %></p>
    <p class="card-text"><%= post.body %></p>
  </div>
</div>

app/views/posts/index.html.erb
<% provide(:title, 'All posts') %>
<div class="text-center jumbotron">
  <h1>Welcome to the Clubhouse</h1>
</div>

<%= will_paginate(@posts, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

<%= render @posts %>

app/views/posts/new.html.erb
<%= provide(:title, 'Create post') %>
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: @post %>
  <div class="jumbotron row justify-content-center">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_field :body, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit post', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, 'error') %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li class="text-danger"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-4">
    <h1><%= @user.name %></h1>
    <%= button_to 'Create a post', new_post_path, method: :get,
        class: 'btn btn-primary' %>
  </div>
</div>